version: '3.8'

services:
  yolo-inference:
    build:
      context: .
      dockerfile: docker/yolo_inference.Dockerfile
    volumes:
      - streams-db:/app/config
      - ./models:/app/models
      - ./TestVideos/:/app/Videos/
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - detector-network
    depends_on:
      db:
         condition: service_started
    deploy:
      replicas: 3
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    container_name: sqlite_db
    volumes:
      - streams-db:/app/config
    networks:
      - detector-network
    command: ["python", "config.py"]

  web-ui:
    build:
      context: .
      dockerfile: docker/web_ui.Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      db:
        condition: service_started
    volumes:
      - streams-db:/app/config
    networks:
      - detector-network

volumes:
  streams-db:

networks:
  detector-network:
    driver: bridge
