version: '3.8'

services:
  yolo-inference:
    build:
      context: .
      dockerfile: docker/yolo_inference.Dockerfile
    volumes:
      - streams-db:/app/config
      - ./models:/app/models
      - ./TestVideos/:/app/Videos/
    networks:
      - detector-network
    depends_on:
      db:
        condition: service_started

  db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    container_name: sqlite_db
    volumes:
      - streams-db:/app/config
    networks:
      - detector-network
    command: ["python", "config.py"]

  web-ui:
    build:
      context: .
      dockerfile: docker/web_ui.Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      db:
        condition: service_started
    volumes:
      - streams-db:/app/config
    networks:
      - detector-network

volumes:
  streams-db:

networks:
  detector-network:
    driver: bridge
