apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-inference
  template:
    metadata:
      labels:
        app: yolo-inference
    spec:
      containers:
        - name: yolo-inference
          image: your-dockerhub/yolo-inference:latest
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_QUEUE_IN
              value: "rtsp-frames"
            - name: RABBITMQ_QUEUE_OUT
              value: "yolo-detections"
